/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercice04;

/**
 *
 * @author delanhese
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        options = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ufName = new javax.swing.JLabel();
        capitalName = new javax.swing.JLabel();
        populationValue = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estados Brasileiros e Bandeiras");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel1.setText("Estados Brasileiros e Bandeiras");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jLabel2.setText("Selecione um estado");

        options.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });

        jLabel3.setText("UF:");

        jLabel4.setText("Capital:");

        jLabel5.setText("Polulação:");

        ufName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ufName.setToolTipText("");

        capitalName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        populationValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(populationValue))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(capitalName))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ufName))
                                .addComponent(options, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(jLabel1))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ufName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(capitalName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(populationValue)))
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsActionPerformed

        Integer selectedOption = options.getSelectedIndex();
        image.setText(String.valueOf(selectedOption));

        switch (selectedOption) {
            case 1:
                populationValue.setText("790.101");
                ufName.setText("AC");
                capitalName.setText("Rio Braco");
                image.setText("Acre");
                break;
            case 2:
                populationValue.setText("3.322.000");
                ufName.setText("AL");
                capitalName.setText("Maceió");
                image.setText("Alagoas");
                break;
            case 3:
                populationValue.setText("751.000");
                ufName.setText("AP");
                capitalName.setText("Macapá");
                image.setText("Amapá");
                break;
            case 4:
                populationValue.setText("3.874.000");
                ufName.setText("AM");
                capitalName.setText("Manaus");
                image.setText("Amazonas");
                break;
            case 5:
                populationValue.setText("14.700.000");
                ufName.setText("BA");
                capitalName.setText("Salvador");
                image.setText("Bahia");
                break;
            case 6:
                populationValue.setText("8.936.431");
                ufName.setText("CE");
                capitalName.setText("Fortaleza");
                image.setText("Ceará");
                break;
            case 7:
                populationValue.setText("2.923.369");
                ufName.setText("DF");
                capitalName.setText("Brasília");
                image.setText("Distrito Federal");
                break;
            case 8:
                populationValue.setText("3.885.000");
                ufName.setText("ES");
                capitalName.setText("Vitória");
                image.setText("Espirito Santo");
                break;
            case 9:
                populationValue.setText("6.523.000");
                ufName.setText("GO");
                capitalName.setText("Goiânia");
                image.setText("Goiás");
                break;
            case 10:
                populationValue.setText("6.523.000");
                ufName.setText("MA");
                capitalName.setText("São Luíz");
                image.setText("Maranhão");
                break;
            case 11:
                populationValue.setText("3.224.000");
                ufName.setText("MT");
                capitalName.setText("Corumba");
                image.setText("Mato Grosso");
                break;
            case 12:
                populationValue.setText("2.620.000");
                ufName.setText("MS");
                capitalName.setText("Campo Grande");
                image.setText("Mato Grosso do Sul");
                break;
            case 13:
                populationValue.setText("20.870.000");
                ufName.setText("MG");
                capitalName.setText("Belo Horizonte");
                image.setText("Minas Gerais");
                break;
            case 14:
                populationValue.setText("8.074.000");
                ufName.setText("PA");
                capitalName.setText("Belém");
                image.setText("Pará");
                break;
            case 15:
                populationValue.setText("3.944.000");
                ufName.setText("PB");
                capitalName.setText("João Pessoa");
                image.setText("Paraíba");
                break;
            case 16:
                populationValue.setText("11.080.000");
                ufName.setText("PR");
                capitalName.setText("Curitiba");
                image.setText("Paraná");
                break;
            case 17:
                populationValue.setText("9.278.000");
                ufName.setText("PE");
                capitalName.setText("Recife");
                image.setText("Pernambuco");
                break;
            case 18:
                populationValue.setText("3.195.000");
                ufName.setText("PI");
                capitalName.setText("Teresina");
                image.setText("Piauí");
                break;
            case 19:
                populationValue.setText("16.460.000");
                ufName.setText("RJ");
                capitalName.setText("Rio de Janeiro");
                image.setText("Rio de Janeiro");
                break;
            case 20:
                populationValue.setText("3.409.000");
                ufName.setText("RN");
                capitalName.setText("Natal");
                image.setText("Rio Grande do Norte");
                break;
            case 21:
                populationValue.setText("11.290.000");
                ufName.setText("RS");
                capitalName.setText("Porto Alegre");
                image.setText("Rio Grande do Sul");
                break;
            case 22:
                populationValue.setText("1.749.000");
                ufName.setText("RN");
                capitalName.setText("Porto Velho");
                image.setText("Rondônia");
                break;
            case 23:
                populationValue.setText("496.396");
                ufName.setText("RO");
                capitalName.setText("Boa Vista");
                image.setText("Roraima");
                break;
            case 24:
                populationValue.setText("7.165.000");
                ufName.setText("SC");
                capitalName.setText("Florianópolis");
                image.setText("Santa Catarina");
                break;
            case 25:
                populationValue.setText("12.333.000");
                ufName.setText("SP");
                capitalName.setText("São Paulo");
                image.setText("São Paulo");
                break;
            case 26:
                populationValue.setText("2.220.000");
                ufName.setText("SE");
                capitalName.setText("Aracajú");
                image.setText("Sergipe");
                break;
            case 27:
                populationValue.setText("1.497.000");
                ufName.setText("TO");
                capitalName.setText("Palmas");
                image.setText("Tocantins");
                break;
            default:
                populationValue.setText("");
                ufName.setText("");
                capitalName.setText("");
                image.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_optionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capitalName;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> options;
    private javax.swing.JLabel populationValue;
    private javax.swing.JLabel ufName;
    // End of variables declaration//GEN-END:variables
}
