version: '3.8'

services:
  mysql:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ifsis
      MYSQL_USER: user
      MYSQL_PASSWORD: root123

