/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package One;

/**
 *
 * @author delanhese
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonQ = new javax.swing.JButton();
        ButtonW = new javax.swing.JButton();
        ButtonE = new javax.swing.JButton();
        ButtonY = new javax.swing.JButton();
        ButtonI = new javax.swing.JButton();
        ButtonP = new javax.swing.JButton();
        ButtonT = new javax.swing.JButton();
        ButtonO = new javax.swing.JButton();
        ButtonR = new javax.swing.JButton();
        ButtonU = new javax.swing.JButton();
        ButtonG = new javax.swing.JButton();
        ButtonK = new javax.swing.JButton();
        ButtonCedilha = new javax.swing.JButton();
        ButtonA = new javax.swing.JButton();
        ButtonF = new javax.swing.JButton();
        ButtonS = new javax.swing.JButton();
        ButtonJ = new javax.swing.JButton();
        ButtonD = new javax.swing.JButton();
        ButtonH = new javax.swing.JButton();
        ButtonL = new javax.swing.JButton();
        ButtonEnter = new javax.swing.JButton();
        ButtonM = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        ButtonN = new javax.swing.JButton();
        ButtonB = new javax.swing.JButton();
        ButtonZ = new javax.swing.JButton();
        ButtonV = new javax.swing.JButton();
        ButtonX = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        ButtonSpace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HangMan Game");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ButtonQ.setText("Q");
        ButtonQ.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonQ.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonQ.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonW.setText("W");
        ButtonW.setDefaultCapable(false);
        ButtonW.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonW.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonW.setPreferredSize(new java.awt.Dimension(44, 44));
        ButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWActionPerformed(evt);
            }
        });

        ButtonE.setText("E");
        ButtonE.setDefaultCapable(false);
        ButtonE.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonE.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonE.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonY.setText("Y");
        ButtonY.setDefaultCapable(false);
        ButtonY.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonY.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonY.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonI.setText("I");
        ButtonI.setDefaultCapable(false);
        ButtonI.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonI.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonI.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonP.setText("P");
        ButtonP.setDefaultCapable(false);
        ButtonP.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonP.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonP.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonT.setText("T");
        ButtonT.setDefaultCapable(false);
        ButtonT.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonT.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonT.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonO.setText("O");
        ButtonO.setDefaultCapable(false);
        ButtonO.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonO.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonO.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonR.setText("R");
        ButtonR.setDefaultCapable(false);
        ButtonR.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonR.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonR.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonU.setText("U");
        ButtonU.setDefaultCapable(false);
        ButtonU.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonU.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonU.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonG.setText("G");
        ButtonG.setDefaultCapable(false);
        ButtonG.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonG.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonG.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonK.setText("K");
        ButtonK.setDefaultCapable(false);
        ButtonK.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonK.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonK.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonCedilha.setText("Ç");
        ButtonCedilha.setDefaultCapable(false);
        ButtonCedilha.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonCedilha.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonCedilha.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonA.setText("A");
        ButtonA.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonA.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonA.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonF.setText("F");
        ButtonF.setDefaultCapable(false);
        ButtonF.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonF.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonF.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonS.setText("S");
        ButtonS.setDefaultCapable(false);
        ButtonS.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonS.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonS.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonJ.setText("J");
        ButtonJ.setDefaultCapable(false);
        ButtonJ.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonJ.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonJ.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonD.setText("D");
        ButtonD.setDefaultCapable(false);
        ButtonD.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonD.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonD.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonH.setText("H");
        ButtonH.setDefaultCapable(false);
        ButtonH.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonH.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonH.setPreferredSize(new java.awt.Dimension(44, 44));
        ButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHActionPerformed(evt);
            }
        });

        ButtonL.setText("L");
        ButtonL.setDefaultCapable(false);
        ButtonL.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonL.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonL.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonEnter.setText("ENTER");
        ButtonEnter.setDefaultCapable(false);
        ButtonEnter.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonEnter.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonEnter.setPreferredSize(new java.awt.Dimension(44, 44));
        ButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnterActionPerformed(evt);
            }
        });

        ButtonM.setText("M");
        ButtonM.setDefaultCapable(false);
        ButtonM.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonM.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonM.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonC.setText("C");
        ButtonC.setDefaultCapable(false);
        ButtonC.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonC.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonC.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonN.setText("N");
        ButtonN.setDefaultCapable(false);
        ButtonN.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonN.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonN.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonB.setText("B");
        ButtonB.setDefaultCapable(false);
        ButtonB.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonB.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonB.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonZ.setText("Z");
        ButtonZ.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonZ.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonZ.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonV.setText("V");
        ButtonV.setDefaultCapable(false);
        ButtonV.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonV.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonV.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonX.setText("X");
        ButtonX.setDefaultCapable(false);
        ButtonX.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonX.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonX.setPreferredSize(new java.awt.Dimension(44, 44));

        ButtonBack.setText("BACK");
        ButtonBack.setDefaultCapable(false);
        ButtonBack.setMaximumSize(new java.awt.Dimension(44, 44));
        ButtonBack.setMinimumSize(new java.awt.Dimension(44, 44));
        ButtonBack.setPreferredSize(new java.awt.Dimension(44, 44));
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonSpace.setText("SPACE");
        ButtonSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSpaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCedilha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonE, ButtonI, ButtonO, ButtonP, ButtonR, ButtonT, ButtonU, ButtonW, ButtonY});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCedilha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonE, ButtonI, ButtonO, ButtonP, ButtonQ, ButtonR, ButtonT, ButtonU, ButtonW, ButtonY});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonWActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHActionPerformed

    private void ButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEnterActionPerformed

    private void ButtonSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSpaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonA;
    private javax.swing.JButton ButtonB;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonCedilha;
    private javax.swing.JButton ButtonD;
    private javax.swing.JButton ButtonE;
    private javax.swing.JButton ButtonEnter;
    private javax.swing.JButton ButtonF;
    private javax.swing.JButton ButtonG;
    private javax.swing.JButton ButtonH;
    private javax.swing.JButton ButtonI;
    private javax.swing.JButton ButtonJ;
    private javax.swing.JButton ButtonK;
    private javax.swing.JButton ButtonL;
    private javax.swing.JButton ButtonM;
    private javax.swing.JButton ButtonN;
    private javax.swing.JButton ButtonO;
    private javax.swing.JButton ButtonP;
    private javax.swing.JButton ButtonQ;
    private javax.swing.JButton ButtonR;
    private javax.swing.JButton ButtonS;
    private javax.swing.JButton ButtonSpace;
    private javax.swing.JButton ButtonT;
    private javax.swing.JButton ButtonU;
    private javax.swing.JButton ButtonV;
    private javax.swing.JButton ButtonW;
    private javax.swing.JButton ButtonX;
    private javax.swing.JButton ButtonY;
    private javax.swing.JButton ButtonZ;
    // End of variables declaration//GEN-END:variables
}
